# https://wiki.shibboleth.net/confluence/display/IDP30/Installation
# ansible-playbook playbook.yml -i hosts -v
# or if you want to run specifieds roles:
# ansible-playbook playbook.yml -i hosts -v --tag common
# inspired by: https://github.com/ConsortiumGARR/idem-tutorials/blob/master/idem-fedops/HOWTO-Shibboleth/Identity%20Provider/Ubuntu/HOWTO%20Install%20and%20Configure%20a%20Shibboleth%20IdP%20v3.2.1%20on%20Ubuntu%20Linux%20LTS%2016.04%20with%20Apache2%20%2B%20Jetty9.md
---
- name: Install Ansible-RT4-ShibIDP on MariaDB
  hosts: all
  become: yes
  vars_files:
    - rt_vars.yml

  vars:
    # If True it will uninstall and purge existing applications and configurations
    # DO NOT DO THAT in production environment
    - purge: true
  
  roles:
    # apt dependencies and certificates
    - { role: common, tags: ["common"] }
    - { role: rt4, tags: ["rt4"] }
