- name: "Uninstall and Purge"
  include_role:
    name: "uninstall"
  when: purge == true
  
- name: Update apt cache
  apt: update_cache=yes
  # apt: update_cache=yes cache_valid_time=86400
  tags: online

- name: Install apt packages
  apt: name={{ item }} state=present
  with_items:
    - perl-doc
    - libgdchart-gd2-xpm
    - build-essential
    - fonts-noto-mono
    - graphviz
    - guile-2.0-libs
    - libann0
    - apache2
    - libapache-session-perl
    - libapache2-mod-fcgid
    - libapache2-mod-perl2
    - libapache2-reload-perl
    - libcdt5
    - libcgraph6
    - libfribidi0
    - libfsplib0
    - libgc1c2
    - libgd3
    - libgsasl7
    - libgts-0.7-5
    - libgts-bin
    - libgvc6
    - libgvpr2
    - libkyotocabinet16v5
    - liblua5.1-0
    - liblzo2-2
    - libmailutils5
    - libossp-uuid16
    - libpq5
    - libtre5
    - libwebp6
    - libxdot4
    - links
    - lynx
    - lynx-common
    - lynx-cur
    - mailutils
    - swaks
    - fonts-noto
    - gsfonts
    - graphviz-doc
    - fonts-dustin
    - libgd-tools
    - libhtml-mason-perl-doc
    - perl
    - uuid
    - tre-agrep
    - xml-twig-tools
    - mailutils-mh
    - mailutils-doc
    - fcgiwrap
    - fonts-noto-mono
    - graphviz
    - guile-2.0-libs
    - libann0
    - libcdt5
    - libcgraph6
    - libfribidi0
    - libfsplib0
    - libgc1c2
    - libgd3
    - libgsasl7
    - libgts-0.7-5
    - libgts-bin
    - libgvc6
    - libgvpr2
    - libkyotocabinet16v5
    - liblua5.1-0
    - liblzo2-2
    - libmailutils5
    - libossp-uuid16
    - libpathplan4
    - libpq5
    - libtre5
    - libwebp6
    - libxdot4
    - links
    - lynx
    - lynx-common
    - lynx-cur
    - mailutils
    - mariadb-server
    # - rt4-apache2
    # - rt4-clients
    # - rt4-db-mysql
    # - rt4-doc-html
    # - rt4-extension-calendar
    # - rt4-extension-customfieldsonupdate
    # - rt4-extension-jsgantt
    # - rt4-extension-repeatticket
    # - rt4-extension-smsnotify
  tags: online

- name: Restart MariaDB
  service: name=mysql state=restarted enabled=yes

- name: "Ensures {{ tmp_upload_dir }} dir exists"
  file: path="{{ tmp_upload_dir }}" state=directory
