- name: "Uninstall and Purge"
  include_role:
    name: "uninstall"
  when: purge == true
  
- name: Update apt cache
  apt: update_cache=yes
  # apt: update_cache=yes cache_valid_time=86400
  tags: online

- name: Install apt packages
  apt: name={{ item }} state=present
  with_items:
    - perl-doc
    - libgdchart-gd2-xpm
    - build-essential
    # - rt4-apache2
    # - rt4-clients
    # - rt4-db-mysql
    # - rt4-doc-html
    # - rt4-extension-calendar
    # - rt4-extension-customfieldsonupdate
    # - rt4-extension-jsgantt
    # - rt4-extension-repeatticket
    # - rt4-extension-smsnotify
    - mariadb-server
  tags: online

- name: Restart MariaDB
  service: name=mysql state=restarted enabled=yes

- name: "Ensures {{ tmp_upload_dir }} dir exists"
  file: path="{{ tmp_upload_dir }}" state=directory
